name: Generate Tiles

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install C Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -y < c-dependencies.txt
      
      - name: Clone and Install Libosmium
        run: |
          git clone https://github.com/osmcode/libosmium.git
          cd libosmium
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Clone and Install Osmium Tool
        run: |
          git clone https://github.com/osmcode/osmium-tool.git
          cd osmium-tool
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Download Map Data
        run: curl --output data.osm.pbf "http://download.geofabrik.de/asia/taiwan-latest.osm.pbf"
      
      - name: Clean Map Data
        run: osmium cat -c changeset -c uid -c user -c version -c timestamp -o cleaned.osm.pbf data.osm.pbf

      - name: Convert Cleaned Map Data into GeoJSON
        run: osmium export cleaned.osm.pbf --bbox=121.27,24.8,122.004,25.3 -o data.geojson
      
      - name: Upload Tiles
        uses: actions/upload-artifact@v4
        with:
          name: data.geojson # The name of the artifact
          path: data.geojson # The path of the directory to upload