name: Generate Tiles

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install C Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -y < c-dependencies.txt

      - name: Clone and Install Osmium Tool
        run: |
          git clone https://github.com/osmcode/osmium-tool.git
          cd osmium-tool
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Install Tippecanoe
        run: |
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          make -j
          sudo make install

      - name: Install Mbutil
        run: pip install mbutil

      - name: Download Map Data
        run: curl --output data.osm.pbf "http://download.geofabrik.de/asia/taiwan-latest.osm.pbf"
      
      - name: Clean Map Data
        run: osmium cat -c changeset -c uid -c user -o cleaned.osm.pbf data.osm.pbf

      - name: Convert Map Data into Mbtiles
        run: tippecanoe -o mb.mbtiles cleaned.osm.pbf
      
      - name: Create a Directory for Tiles
        run: mkdir tiles

      - name: Extract Tiles from Mbtiles into Smaller PBFs
        run: mb-util mb.mbtiles tiles/ --image_format=pbf
      
      - name: Upload Tiles
        uses: actions/upload-artifact@v4
        with:
          name: tiles # The name of the artifact
          path: tiles # The path of the directory to upload